use_frameworks!

target 'VTextView_Example' do
  pod 'VTextView', :path => '../'
  pod 'SnapKit'
  pod 'RxCocoa'
  pod 'RxSwift'

  target 'VTextView_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
